# Generated by Django 4.1.4 on 2023-04-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pin', models.CharField(max_length=6, null=True)),
                ('courses_available', models.CharField(choices=[('B.SC.GEOGRAPHY', 'B.SC.GEOGRAPHY'), ('B.SC.MICROBIOLOGY', 'B.SC.MICROBIOLOGY'), ('B.SC.COMPUTER SCIENCE', 'B.SC.COMPUTER SCIENCE'), ('B.SC.PHYSICS', 'B.SC.PHYSICS'), ('B.SC.MATHEMATICS', 'B.SC.MATHEMATICS'), ('B.COM IT', 'B.COM IT'), ('B.COM CA', 'B.COM CA'), ('B.COM', 'B.COM'), ('B.B.A BUSINESS ADMINISTRATION', 'B.B.A BUSINESS ADMINISTRATION'), ('BBA.CA', 'BBA.CA'), ('B.A ENGLISH', 'B.A ENGLISH'), ('B.COM', 'B.COM'), ('B.Sc.Cs', 'B.Sc.Cs'), ('BCA', 'BCA')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sample_images')),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depts', models.CharField(max_length=100)),
            ],
        ),
       
        migrations.CreateModel(
            name='staffdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_image', models.ImageField(null=True, upload_to='staff_images')),
                ('depts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
        migrations.CreateModel(
            name='hods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=100)),
                ('hod_image', models.ImageField(null=True, upload_to='hod_images')),
                ('depts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
    ]
