# Generated by Django 4.1.4 on 2023-04-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
    ]
