# Generated by Django 4.1.4 on 2023-04-30 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_feedback_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')]),
        ),
    ]
