# Generated by Django 4.1.4 on 2023-04-30 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_admission_firstname_alter_admission_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[789]\\d{9}|(\\d[ -]?){10}\\d$', 'Enter a Valid Indian Phone Number')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='pin',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$', 'Enter a valid pin code')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')]),
        ),
        migrations.AlterField(
            model_name='hods',
            name='hod_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')]),
        ),
        migrations.AlterField(
            model_name='staffdetail',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')]),
        ),
    ]
